### ISSUE TITLE
CT image preprocess

### ISSUE THREAD

**Issue by liuziyang1106** [sitiny/mr-to-pct#2]
Hello author, you have done a great job generating CT images through T1w images. I have also been trying to use deep learning models for similar research recently, but the results have not been very good. I would like to ask you, how do you preprocess CT images? I believe CT image pixel values are in HU units, so direct standardization may not be very suitable. I would like to consult with you.

**Comment by sitiny** [comment]
Hi Liu Ziyang, thanks for your message and interest in my work. The details of the CT preprocessing are in the supplementary material of the paper linked at the bottom of the page; I provide the link here for your reference: https://doi.org/10.1016/j.brs.2023.01.838. Please could you contact me by email if you have further questions? I will close this comment now as it is not an issue with the code.
