### ISSUE TITLE
MONAI version

### ISSUE THREAD

**Issue by javierlopezrodriguez** [sitiny/mr-to-pct#4]
Hello,

Thank you for developing this great tool!

I am encountering an issue while using the current MONAI version (1.3.2) installed via pip install monai. Specifically, I do not have access to certain functions, such as AddChannel. As I have seen in the MONAI documentation, AddChannel was available in earlier versions, but it seems to have been removed or replaced at some point in time.

Could you please provide the version number of the MONAI library that is compatible with your tool? I would like to know that I am using the correct library version in order to ensure reproducibility.

Thank you in advance!

**Comment by sitiny** [comment]
Hi javierlopexrodriguez,

Sorry for the delay in responding. I was unable to track down the last working version as I no longer have access to the computer I developed this on, but I *think* it was 1.1. Please let me know if that works for you. I'll also add it to the main documentation page.

Best,
Siti
